# -*- coding: utf-8 -*-
"""Quỳnh Phương 3_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uFEK-UPcfQC6fOvSm78sUNjEJjgY6-P

# =============================
# BÀI TẬP 3: Luật kết hợp cho hệ khuyến nghị
# =============================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder
import os
import urllib.request
import zipfile

ml_100k_url = 'https://files.grouplens.org/datasets/movielens/ml-100k.zip'
ml_100k_zip = 'ml-100k.zip'
ml_100k_folder = 'ml-100k'

if not os.path.exists(ml_100k_folder):
    if not os.path.exists(ml_100k_zip):
        print('Downloading MovieLens 100K dataset...')
        urllib.request.urlretrieve(ml_100k_url, ml_100k_zip)
    print('Extracting MovieLens 100K dataset...')
    with zipfile.ZipFile(ml_100k_zip, 'r') as zip_ref:
        zip_ref.extractall('.')

# Đọc dữ liệu đánh giá
ratings_cols = ['userID', 'itemID', 'rating', 'timestamp']
ratings_df = pd.read_csv('ml-100k/u.data', sep='\t', names=ratings_cols, encoding='latin-1')

ratings_df.head()

# TODO: Chuyển đổi dữ liệu đánh giá thành dữ liệu giao dịch
# 1. Lọc các đánh giá cao (rating >= 4)
high_rating_df = ratings_df[ratings_df['rating'] >= 4]
# Lưu dữ liệu đã lọc ra file CSV (không ghi index để tránh cột số thứ tự)
high_rating_df.to_csv('high_ratings.csv', index=False)
# Đọc lại file đã lọc
filtered_df = pd.read_csv('high_ratings.csv')
# Kiểm tra kết quả
filtered_df.head()

# TODO: Áp dụng thuật toán Apriori
# 1. Chuyển đổi dữ liệu giao dịch thành định dạng ma trận nhị phân
#Tạo danh sách giao dịch: mỗi người dùng -> danh sách phim (ID)
transactions = high_rating_df.groupby('userID')['itemID'].apply(list)

#  Mã hóa danh sách giao dịch thành ma trận nhị phân
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_array, columns=te.columns_)

# 2. Tìm tập mục thường xuyên
frequent_itemsets = apriori(df_encoded, min_support=0.1, use_colnames=True)

# 3. Tạo luật kết hợp
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.4)

# Xem kết quả
rules.head()

# TODO: Đánh giá chất lượng luật
# 1. Phân tích độ hỗ trợ, độ tin cậy và độ nâng
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

# Lọc top 10 luật theo lift
top_rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]\
                .sort_values(by='lift', ascending=False).head(10)

# Hiển thị bảng đẹp bằng plotly (đã ép kiểu int → str)
fig = go.Figure(data=[go.Table(
    header=dict(values=["Antecedents", "Consequents", "Support", "Confidence", "Lift"],
                fill_color='lightblue',
                align='left'),
    cells=dict(values=[
        [', '.join([str(i) for i in a]) for a in top_rules['antecedents']],
        [', '.join([str(i) for i in c]) for c in top_rules['consequents']],
        top_rules['support'].round(3),
        top_rules['confidence'].round(3),
        top_rules['lift'].round(3)
    ],
    fill_color='lavender',
    align='left'))
])
fig.update_layout(title="Top 10 Association Rules by Lift", width=1000, height=400)
fig.show()

# 2. Trực quan hóa các luật tốt nhất
plt.figure(figsize=(10,6))
sns.scatterplot(data=rules, x='support', y='confidence', size='lift', hue='lift', sizes=(20, 200), palette='viridis')
plt.title('Scatter plot of Association Rules')
plt.xlabel('Support')
plt.ylabel('Confidence')
plt.grid(True)
plt.show()

# TODO: Xây dựng hệ khuyến nghị dựa trên luật
# def recommend_movies(user_movies, rules, top_n=10):
#     recommendations = []
#     for _, rule in rules.iterrows():
#         antecedents = set(rule['antecedents'])
#         if antecedents.issubset(user_movies):
#             for movie in rule['consequents']:
#                 if movie not in user_movies:
#                     recommendations.append((movie, rule['confidence'], rule['lift']))
#
#     # Sắp xếp theo độ tin cậy và độ nâng
#     recommendations.sort(key=lambda x: (x[1], x[2]), reverse=True)
#     return recommendations[:top_n]
# Hàm khuyến nghị phim dựa trên luật kết hợp
def recommend_movies(user_movies, rules, top_n=10):
    recommendations = []
    for _, rule in rules.iterrows():
        antecedents = set(rule['antecedents'])
        if antecedents.issubset(user_movies):
            for movie in rule['consequents']:
                if movie not in user_movies:
                    try:
                        movie_int = int(movie)
                        recommendations.append((movie_int, rule['confidence'], rule['lift']))
                    except:
                        continue  # bỏ qua nếu không chuyển được sang int

    # Sắp xếp theo độ tin cậy và độ nâng
    recommendations.sort(key=lambda x: (x[1], x[2]), reverse=True)
    return recommendations[:top_n]


# ================================
# Gọi thử hàm khuyến nghị
# ================================

user_movies = {1, 50}  # Giả sử người dùng đã xem phim có ID 1 và 50

# Gọi hàm khuyến nghị
recommendations = recommend_movies(user_movies, rules, top_n=10)

# Đọc dữ liệu tên phim
movies_df = pd.read_csv(
    'ml-100k/u.item',
    sep='|',
    encoding='latin-1',
    header=None,
    usecols=[0, 1],
    names=['itemID', 'title']
)
movie_dict = dict(zip(movies_df['itemID'], movies_df['title']))

# In kết quả
if recommendations:
    print("🎬 Gợi ý phim cho người dùng:")
    for movie, confidence, lift in recommendations:
        movie_name = movie_dict.get(movie, f'Phim ID {movie}')
        print(f"- {movie_name} | Độ tin cậy: {confidence:.2f} | Độ nâng: {lift:.2f}")
else:
    print("⚠️ Không có gợi ý phù hợp với lịch sử người dùng.")